### ISSUE TITLE
Missing comma in totalstation.py

### ISSUE THREAD

**Issue by TodWell** [dabamos/openadms#3]
Hi again, in `totalstation.py`, there is a comma missing in line 1120, which prevents the SerialMeasurementProcessor from working.
`
response_sets['slopeDist'] = Obs.create_response_set('float' 'm', dist)
`

Thanks

**Comment by interkosmos** [comment]
Thank you. Has been fixed with commit 2ec3c310b9229c82ead3952abe826f1eef15b20c.
