### ISSUE TITLE
Timeout on port "/dev/ttyACM1" after 1.0 s

### ISSUE THREAD

**Issue by geovey** [dabamos/openadms#5]
It runs normally, but there will always be "timeout" occasionally, resulting in incomplete data reading. Even if I set timeout=0.0, it still happens. How to solve this?

**Comment by interkosmos** [comment]
Can you describe the setup and what commands you are sending to `/dev/ttyACM1`?

**Comment by geovey** [comment]
Ok, I set up a GNSS receiver to output 1hz gga information, and read the gga statement through the serial port /dev/ttyACM1;
"com1": {
	"port": "/dev/ttyACM1",
	"baudRate": 115200,
	"byteSize": 8,
	"stopBits": 1,
	"parity": "none",
	"timeout": 0.0,
	"softwareFlowControl": false,
	"hardwareFlowControl": false,
	"maxAttempts": 1
}

**Comment by interkosmos** [comment]
What happens when you increase the timeout value?

**Comment by geovey** [comment]
The number of characters read is incomplete and missing

**Comment by geovey** [comment]
![0914](https://user-images.githubusercontent.com/29365168/93082530-a7a6bf00-f6c3-11ea-919c-47a9e1cf4d5a.jpg)

**Comment by interkosmos** [comment]
Is the `responseDelimiter` of your observation set to `\r\n` to match the end of each response? This is most likely an issue with a wrong regex (`responsePattern`) or a wrong delimiter.
